In [16]:
import numpy as np

In [13]:
# we can create NumPy array from list
arr1 = np.array([1,2,4,6,7,8])
print(arr1, type(arr1), arr1.dtype , arr1.shape)

arr2 = np.array([1,2,4,6,7,8,"hello","Rahul"])
print(arr2, type(arr2), arr2.dtype , arr2.shape)

arr3 = np.array([1,2,4,6,7,8,"hello",None,"Rahul"])
print(arr3, type(arr3), arr3.dtype , arr3.shape)


print('\n')
# 2-D array
arr4 = np.array([[1,3,5],[4,2,2],[2,4,6]])
print(arr4, type(arr4), arr4.dtype , arr4.shape)

[1 2 4 6 7 8] <class 'numpy.ndarray'> int64 (6,)
['1' '2' '4' '6' '7' '8' 'hello' 'Rahul'] <class 'numpy.ndarray'> <U21 (8,)
[1 2 4 6 7 8 'hello' None 'Rahul'] <class 'numpy.ndarray'> object (9,)


[[1 3 5]
 [4 2 2]
 [2 4 6]] <class 'numpy.ndarray'> int64 (3, 3)


**


  Or we can create Numpy array from scratch using different-different
  built-in function or methods 
**

In [28]:
arr1 = np.zeros((3,3) , dtype = "int64") #prefill with zero
print(arr1)  

arr1 = np.zeros((3,4)) # prefill with zero
print(arr1)

arr1 = np.zeros((5,) , dtype = "int64") # 1-D array, prefill with zero
print(arr1 , arr1.shape)


arr2 = np.ones((2,2)) # prerfill with one
print(arr2 , arr2.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0 0 0 0 0] (5,)
[[1. 1.]
 [1. 1.]] (2, 2)


In [29]:
arr3 = np.full((3,3) , 10) # prefill with value
print(arr3, arr3.shape)

[[10 10 10]
 [10 10 10]
 [10 10 10]] (3, 3)


In [32]:
arr3 = np.eye(3 , dtype = "int64") # used for identity matrix
print(arr3, arr3.shape)

[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)


In [38]:
# Range elements
arr3 = np.arange(0,11,2)
print(arr3, arr3.shape)

arr3 = np.arange(0,11,1)
print(arr3, arr3.shape)

arr3 = np.arange(0,11,4)
print(arr3, arr3.shape)

[ 0  2  4  6  8 10] (6,)
[ 0  1  2  3  4  5  6  7  8  9 10] (11,)
[0 4 8] (3,)


In [46]:
arr = np.linspace(1,100,4)
print(arr , arr.shape)

[  1.  34.  67. 100.] (4,)


In [52]:
# Properties of NumPy array

arr = np.array([[1,3,1] , [3,5,0] , [3,4,1]])
print(arr.shape) # it returns simension m x n
print(arr.dtype) # it returns data type 
print(arr.size) # total no. of elements in array
print(arr.ndim) # it returns no. of dimension 

# type casting
float_arr = arr.astype(np.float64)
print(float_arr , float_arr.dtype)

(3, 3)
int64
9
2
[[1. 3. 1.]
 [3. 5. 0.]
 [3. 4. 1.]] float64
