In [4]:
# Operations on NumPy arrays

import numpy as np

In [10]:
arr = np.array([[1,2,3],[1,1,1],[3,0,1],[2,3,2]])
print(arr , arr.shape)

reshape = arr.reshape(3,4)
print(reshape , reshape.shape)

# flattend array --> we can convert 2-d array into 1-d array
arr1 = np.array([[1,31,1],[4,5,3]])
flattened = arr1.flatten()
print(flattened , flattened.shape)

[[1 2 3]
 [1 1 1]
 [3 0 1]
 [2 3 2]] (4, 3)
[[1 2 3 1]
 [1 1 3 0]
 [1 2 3 2]] (3, 4)
[ 1 31  1  4  5  3] (6,)


In [24]:
# Indexing of array

arr = np.array([1,2,2,1,3,1,2,4,6,3,92])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])

print('\n')
for element in arr:
    print(element)

print('\n')
for element in range(arr.size):
    print(arr[element])


1
2
2
1


1
2
2
1
3
1
2
4
6
3
92


1
2
2
1
3
1
2
4
6
3
92


In [30]:
arr = np.array([[1,3,1] , [3,5,0] ])
print(arr[0][2])

1


In [35]:
# Fancy Indexing
arr = np.array([2,21,3,5,7,3,22])
idx = [0,2,3,2,5,1]
print(arr[idx])

# Boolean Indexing
print(arr[arr>3])
print(arr[arr%2 == 0])
print(arr[arr%2 != 0])

[ 2  3  5  3  3 21]
[21  5  7 22]
[ 2 22]
[21  3  5  7  3]


In [37]:
# Slicing
arr = np.array([1,34,55,2,5,90,0,3])
print(arr)
print(arr[:])
print(arr[2:5])
print(arr[2:])
print(arr[:4])
print(arr[::2])
print(arr[1:6:3]) # [start : end : step]

[ 1 34 55  2  5 90  0  3]
[ 1 34 55  2  5 90  0  3]
[55  2  5]
[55  2  5 90  0  3]
[ 1 34 55  2]
[ 1 55  5  0]
[34  5]


In [43]:
# Copy vs View
nums = [1,2,3,5,6,8]
sub_list = nums[0:3]
sub_list[1] = 35
print(sub_list)
print(nums)

print('\n')

arr = np.array([1,2,3,5,6,8])
sub_arr = arr[0:3]
sub_arr[1] = 35
print(sub_arr)
print(arr)

print('\n')

arr = np.array([1,2,3,5,6,8])
sub_arr = arr[0:3].copy() #if we want to actually create copy 
# and we are not copying the entire array we are copying the view of the slice array into variable
sub_arr[1] = 35
print(sub_arr)
print(arr)

[1, 35, 3]
[1, 2, 3, 5, 6, 8]


[ 1 35  3]
[ 1 35  3  5  6  8]


[ 1 35  3]
[1 2 3 5 6 8]
