In [1]:
# Multi-dimension Array

In [27]:
import numpy as np

In [28]:
arr2D  = np.array([[1,2,3],[3,3,1],[9,4,1]]) 
print(arr2D)

[[1 2 3]
 [3 3 1]
 [9 4 1]]


In [29]:
print("Sum of all element of matrix",np.sum(arr2D))

Sum of all element of matrix 27


In [30]:
print("Sum of columns",np.sum(arr2D , axis = 0))

Sum of columns [13  9  5]


In [31]:
print("Sum of rows",np.sum(arr2D , axis = 1))

Sum of rows [ 6  7 14]


In [32]:
# Slicing concept
# here also we can get particular part of an array
# like if i want to print the only 3 and 4 value from my array name arr2D so that i can access them like that
print(arr2D[1: , 1:2])

[[3]
 [4]]


In [33]:
# 3-D Array
arr3D = np.array([[[1,2] , [2,0] , [7,4]] ,[[5,4] , [3,5] , [9,0]]])
print(arr3D , arr3D.shape)
print(np.sum(arr3D))

# Indexing
print(arr3D[0,2,1])

# Slicing
print("first row from both the layer  ",arr3D[:,0,:])
print("first column from both the layer  ",arr3D[:,:,0])

# Data manipulation
arr3D[:,:,0] = 99
print(arr3D)

[[[1 2]
  [2 0]
  [7 4]]

 [[5 4]
  [3 5]
  [9 0]]] (2, 3, 2)
42
4
first row from both the layer   [[1 2]
 [5 4]]
first column from both the layer   [[1 2 7]
 [5 3 9]]
[[[99  2]
  [99  0]
  [99  4]]

 [[99  4]
  [99  5]
  [99  0]]]
